project_name: MixCon3D
clip_embed_dim: 1280
clip_embed_version: OpenCLIP

model:
  name: MinkResNet34 
  in_channel: 6
  out_channel: ${clip_embed_dim}
  embedding_channel: 1024
  voxel_size: 0.02

training:
  debug: False
  use_openclip_optimizer_scheduler: True
  lr: 0.006
  min_lr: 0.003
  lr_decay_step: 10000
  lr_decay_rate: 0.967
  beta1: 0.9
  beta2: 0.999
  eps: 1.0e-8
  warmup_epoch: 10
  max_epoch: 200
  log_freq: 10
  save_freq: 50
  lambda_img_contras: 1
  lambda_text_contras: 1
  precision: supress
  use_image_proj: True 
  use_text_proj: True
  share_proj: True
  image_text_align: True
  logit_scale_init: 14.28
  logit_scale_fix: False
  img_loss_mode: Avg
  pc_img_to_text: True
  use_mask: False
  ema: True
  ema_decay: 0.9995
  sparseconv_ema: False
  mask_threshold: 0.1
  use_MLP: False
  loss_avg: False

dataset:
  image_feat_mode: Multiple
  inference_image_feat_mode: Multiple
  image_amount: 4
  folder: "data3"
  name: Four
  train_split: meta_data/split/train_all.json
  train_partial: -1
  num_points: 10000 
  num_workers: 6
  accum_freq: 1
  train_batch_size: 64
  use_knn_negative_sample: False
  negative_sample_num: 1
  knn_path: meta_data/point_feat_knn.npy
  y_up: True
  normalize: True
  random_z_rotate: True
  use_color: True
  rgb_random_drop_prob: 0.5
  augment: True
  text_source: [text, caption, retrieval_text] 
  use_text_filtering: True
  use_prompt_engineering: True
  gpt4_filtering_path: meta_data/gpt4_filtering.json

modelnet40:
  test_split: meta_data/modelnet40/test_split.json
  test_pc: meta_data/modelnet40/test_pc.npy
  num_points: 10000 
  num_workers: 2
  test_batch_size: 32
  clip_feat_path: meta_data/modelnet40/cat_name_pt_feat.npy
  y_up: True

objaverse_lvis:
    split: meta_data/split/lvis.json
    clip_feat_path: meta_data/lvis_cat_name_pt_feat.npy
    num_points: 10000 
    num_workers: 6
    batch_size: 32
    y_up: True
    normalize: True
    use_color: True

scanobjectnn:
  data_path: meta_data/scanobjectnn/xyz_label.npy 
  num_points: 10000 
  num_workers: 2
  test_batch_size: 32
  clip_feat_path: meta_data/scanobjectnn/cat_name_pt_feat.npy
  y_up: True
  
